#!/usr/bin/env bash
show_menu(){
normal=`echo "\033[m"`
    menu=`echo "\033[36m"` #Blue
    number=`echo "\033[33m"` #yellow
    bgred=`echo "\033[41m"`
    fgred=`echo "\033[31m"`
YELLOW='\033[1;33m'
printf "${menu}     © ᴘᴇɴᴇᴛʀᴀᴛᴏʀs                  ᴄᴏʀᴘᴏʀᴀᴛɪᴏɴ ©      "
printf "${menu}          ♛ α cσмρℓεтεℓү αυтσмαтε∂ ρяσנεcт ♛         "
cat /data/data/com.termux/files/home/Trident/pytransform/Trident
    ./pytransform/header
    
    printf "\n${menu}████████████████████████████████████████████████████████${normal}\n"
    printf "\n${menu}██${number} 1)${menu} ʙʏᴘᴀss ᴋᴏʀᴇᴀ ${normal}\n\n"
    printf "${menu}██${number} 2)${menu} ʙʏᴘᴀss ɢʟᴏʙᴀʟ ${normal}\n\n"
    printf "${menu}██${number} 3)${menu} ᴄʟᴇᴀɴ ʟᴏɢs ${normal}\n\n"
    printf "${menu}██${number} 4)${menu} ʀᴇsᴇᴛ ɢᴜᴇsᴛ ${normal}\n\n"
    printf "${menu}██${number} 5)${menu} ᴄʜᴀɴɢᴇ ᴅɴs 𝟾.𝟾.𝟾.𝟾${normal}\n\n"
    printf "${menu}████████████████████████████████████████████████████████${normal}\n"
    printf "\n${fgred}Please enter a menu option and enter or ${fgred}x to exit. ${normal}"
    read opt
}

option_picked(){
    msgcolor=`echo "\033[01;31m"` # bold red
    normal=`echo "\033[00;00m"` # normal white
    message=${@:-"${normal}Error: No message passed"}
    printf "${msgcolor}${message}${normal}\n"
}

clear
echo " "
echo " "
show_menu
while [ $opt != '' ]
    do
    if [ $opt = '' ]; then
      exit;
    else
      case $opt in
        1) clear;
            option_picked "Pubg Kr Bypass\n";
            printf "Starting Bypass...\n";
            sleep 2
            ./oneclick
            sleep 2
            echo " "
            echo "Exiting To Driver Code"
            sleep 2
            clear
            show_menu;
        ;;
        2) clear;
            option_picked "Global Bypass\n";
            printf "Bypassing Global...\n";
            ./global
            sleep 2
            echo "Exiting To Driver Code"
            sleep 2
            clear
            show_menu;
        ;;
        3) clear;
            option_picked "Log Cleaner\n";
            printf "Cleaning Logs...\n";
            echo " "
            ./progress
            ./cleaner
            sleep 2
            echo " "
            echo "Exiting To Driver Code"
            sleep 2
            clear
            show_menu;
        ;;
        4) clear;
            option_picked "Guest Reset\n";
            printf "Resetting Your Guest Account...\n";
            echo " "
            KR="/data/data/com.pubg.krmobile/shared_prefs/device_id.xml"
            kill com.pubg.krmobile 2> /dev/null
            rm -rf $KR
            echo "<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
    <string name=\"random\"></string>
    <string name=\"install\"></string>
    <string name=\"uuid\">$RANDOM$RANDOM-$RANDOM-$RANDOM-$RANDOM-$RANDOM$RANDOM$RANDOM</string>
</map>" > $KR
./progress
sleep 2
            echo " "
            echo "Exiting To Driver Code"
            sleep 2
            clear
            show_menu;
        ;;
         5) clear;
            option_picked "Dns Changer\n";
            printf "Changing Dns...\n";
            ./pytransform/__pycache__/google
            echo " "
            printf "Dns Changed To Google 8.8.8.8 On Port 53\n";
           sleep 2
            echo "Exiting To Driver Code"
            sleep 2
            clear
             show_menu;
        ;;
        x)
        
printf "${YELLOW}Created by :-\n"
printf "\n${YELLOW}________________________________________________________"
printf "\n${YELLOW}           ______             _                 "
printf "\n${YELLOW}          / _____)           | |                "
printf "\n${YELLOW}         ( (____  _____  ____| |  _ _____  ____ "
printf "\n${YELLOW}          \____ \(____ |/ ___| |_/ (____ |/ ___)"
printf "\n${YELLOW}          _____) / ___ | |   |  _ (/ ___ | |    "
printf "\n${YELLOW}         (______/\_____|_|   |_| \_\_____|_|  "
printf "\n${YELLOW}________________________________________________________"
        exit;
        ;;
        \n)exit;
        ;;
        *)clear;
            option_picked "Pick an option from the menu";
            show_menu;
        ;;
      esac
    fi
done
