#!/data/data/com.termux/files/usr/bin/python
import subprocess
from distutils.dir_util import copy_tree
import os

subprocess.call(['chmod', '-R', '664', '/data/media/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SrcVersion.ini'])
subprocess.call(['chmod', '-R', '664', '/data/media/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android'])
subprocess.call(['chmod', '-R', '664', '/data/media/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks'])
subprocess.call(['chmod', '-R', '664', '/data/media/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs'])
subprocess.call(['chmod', '-R', '664', '/data/media/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/UpdateInfo'])
subprocess.call(['chmod', '-R', '664', '/data/media/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Pandora'])
subprocess.call(['chmod', '-R', '664', '/data/media/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/PufferTmpDir'])
subprocess.call(['chmod', '-R', '664', '/data/media/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Intermediate/SaveGames'])
subprocess.call(['chmod', '-R', '664', '/data/media/0/Android/data/com.pubg.krmobile/cache'])
